language: node_js

node_js:
  - stable

branches:
  except:
    - gh-pages

install:
  - npm install

script:
  - npm run cichecks

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
