name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Upgrade Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: NPM install
        run: npm ci
      - name: Build
        run: npm start
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --dry-run